"""added type of subscription to define stock or crypto

Revision ID: 3f9c82ff10b6
Revises: e8036e273f1a
Create Date: 2025-05-27 20:44:05.753277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f9c82ff10b6'
down_revision: Union[str, None] = 'e8036e273f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('check_type', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('what_to_check', sa.String(), nullable=False))
    op.drop_column('notifications', 'crypto_name')
    op.add_column('subscritions', sa.Column('check_type', sa.String(), nullable=False))
    op.add_column('subscritions', sa.Column('what_to_check', sa.String(), nullable=False))
    op.drop_column('subscritions', 'crypto_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscritions', sa.Column('crypto_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('subscritions', 'what_to_check')
    op.drop_column('subscritions', 'check_type')
    op.add_column('notifications', sa.Column('crypto_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'what_to_check')
    op.drop_column('notifications', 'check_type')
    # ### end Alembic commands ###
