"""created subscription table

Revision ID: 4eeec099c6b8
Revises: 3c3fe3a6a530
Create Date: 2025-05-25 20:40:36.236265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eeec099c6b8'
down_revision: Union[str, None] = '3c3fe3a6a530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscrition_more')
    op.drop_table('subscrition_less')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscrition_less',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crypto_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name=op.f('subscrition_less_uid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscrition_less_pkey'))
    )
    op.create_table('subscrition_more',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crypto_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name=op.f('subscrition_more_uid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscrition_more_pkey'))
    )
    # ### end Alembic commands ###
