"""created tables for tests

Revision ID: 80d3a654ea78
Revises: 3f9c82ff10b6
Create Date: 2025-05-28 22:14:52.000751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80d3a654ea78'
down_revision: Union[str, None] = '3f9c82ff10b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'check_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notifications', 'what_to_check',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscritions', 'check_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('subscritions', 'what_to_check',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscritions', 'what_to_check',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('subscritions', 'check_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'what_to_check',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notifications', 'check_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
