"""added currency field to subscriptions table

Revision ID: 90ce16b9133b
Revises: 4eeec099c6b8
Create Date: 2025-05-25 22:53:43.038176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ce16b9133b'
down_revision: Union[str, None] = '4eeec099c6b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscritions', sa.Column('currency', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscritions', 'currency')
    # ### end Alembic commands ###
