"""created notification table, added premium field for users

Revision ID: d8d71b533d3d
Revises: 90ce16b9133b
Create Date: 2025-05-27 00:15:08.108287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d71b533d3d'
down_revision: Union[str, None] = '90ce16b9133b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('crypto_name', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('operator', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('value', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('currency', sa.String(), nullable=False))
    op.drop_constraint(op.f('notifications_sub_fkey'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'sub')
    op.add_column('users', sa.Column('premium', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium')
    op.add_column('notifications', sa.Column('sub', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_sub_fkey'), 'notifications', 'subscritions', ['sub'], ['id'])
    op.drop_column('notifications', 'currency')
    op.drop_column('notifications', 'value')
    op.drop_column('notifications', 'operator')
    op.drop_column('notifications', 'crypto_name')
    # ### end Alembic commands ###
