"""added created_at field for notifications table

Revision ID: e8036e273f1a
Revises: d8d71b533d3d
Create Date: 2025-05-27 00:43:22.988748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8036e273f1a'
down_revision: Union[str, None] = 'd8d71b533d3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('users', 'premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###
