name: Crypto Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest
      run: PYTHONPATH=. pytest ./__tests__/crypto_tests.py
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PWD: ${{ secrets.DB_PWD }}
        DB_CONN_LINE: ${{ secrets.DB_CONN_LINE }}
        GECKO_API_KEY: ${{ secrets.GECKO_API_KEY }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
        MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        STRIPE_PUBLISH_KEY: ${{ secrets.STRIPE_PUBLISH_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_WEBHOOK_KEY: ${{ secrets.STRIPE_WEBHOOK_KEY }}
      working-directory: ./
      continue-on-error: false