name: Crypto Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker Image
        run: | 
          docker build -t tracker-tests .

      - name: Docker image saving
        run: |
          docker save tracker-tests | gzip > tracker-tests.tar.gz

      - uses: actions/upload-artifact@v3 
        with:
          name: tracker-tests-image
          path: tracker-tests.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          docker run --rm -e PYTHONPATH=. tracker-tests pytest ./__tests__ -s -v
        working-directory: ./
        continue-on-error: false
        